config/routes.rb
Rails.application.routes.draw do
  resources :events do
    member do
      post "rsvp"
      post "cancel"
    end
  end

  resources :teams do
    member do
      post "add_player"
      post "message"
      get "team_feeds"
      put "update_player"
      delete "delete_player"
    end

    collection do
      post "join"
      get "check_code"
    end
  end
  resources :team_avatars
  
  resources :players
  resources :player_avatars

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  resources :users do
    member do
      put "update_avatar"
      get "team_feeds"
    end
  end

  get "/dashboard", :to => "static#dashboard"
  get "/invitation_response", :to => "static#invitation_response"
  post "/sms_response", :to => "static#sms_response"
  get "/welcome", :to => "static#welcome"

  get "/settings", :to => "users#edit"
  root "static#landing"
  post '/email_processor' => 'griddler/emails#create'

end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable, :omniauthable,
			:recoverable, :rememberable, :trackable, :validatable

	has_many :identities, :dependent => :destroy
	has_many :teams_users
	has_many :teams, through: :teams_users
	has_many :team_avatars, :dependent => :destroy
	has_many :player_avatars, :dependent => :destroy
	has_many :event_invitations, :foreign_key => "sender_id", :dependent => :destroy
	has_many :event_invitations, :foreign_key => "reciever_id", :dependent => :destroy
	has_many :rsvps, :dependent => :destroy
	has_many :team_messages, :dependent => :destroy

	before_save do
		# user name
		self.first_name = self.first_name.downcase if self.first_name
		self.last_name = self.last_name.downcase if self.last_name
		self.name = "#{self.first_name} #{self.last_name}" if self.name.nil? || self.name.empty?
		self.name = self.name.downcase if self.name
		
		
		# other details
		self.gender = self.gender.downcase if self.gender
		self.gender = nil unless GENDER.include?(self.gender)

		self.city = self.city.downcase if self.city
		self.country = self.country.downcase if self.country
		self.country = nil unless COUNTRIES.collect{|code| code.first.downcase}.include?(self.country)
		self.state = self.state.downcase if self.state
		self.state = nil unless STATES.collect{|code| code.first.downcase}.include?(self.state)
	end

	validate :phone_number_with_code, :if => "phone.present?"
	validates :phone, :uniqueness => {message: "Player with this phone already exists."}, :if => "phone.present?"
	
	attr_accessor :login

	def self.find_or_create(auth)

		# If user exists then update else create new user
		email = auth.info.email || auth.uid + "@twitter.com"
		user = User.where("email = '#{email}'").first_or_initialize
		user.email = email
		user.name = auth.info.name
		user.save!(:validate => false)

		user
	end

	def get_all_events
		events = Array.new
		self.teams.each do |team|
			events = events + team.events
		end
		events.uniq.sort_by{|e| [e.date,e.time]}.group_by(&:date)
	end

	def is_team_admin?(team)
		self.teams.include?(team)
	end

	def get_all_message_feeds(teams)
		message_feeds = []
		teams.each do |team|
			message_feeds += team.team_messages
		end

		message_feeds
	end

	private
	# login using email or mobile
	def self.find_for_database_authentication(warden_conditions)
		conditions = warden_conditions.dup
		if login = conditions.delete(:login)
			where(conditions).where(["phone = :value OR lower(email) = :value", { :value => login.downcase }]).first
		else
			where(conditions).first
		end
	end

	def phone_number_with_code
		# extracting phone number by ignoring all special and normal charaters
		number = self.phone.gsub(/[^\d]/, '')
		if number.length == 10
			self.phone = "+1" + number
		elsif number.length == 11 and number.start_with?("1")
			self.phone = "+" + number
		elsif number.length == 12 and number.start_with?("+1")
			self.phone = number
		else
			errors.add(:phone, "Please enter 10 digit valid phone number")
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :destroy, :update_avatar]
	before_filter :authenticate_user!
	respond_to :html

	def index
		redirect_to user_path(current_user)
	end

	def show
		@user = User.find(params[:id])
		respond_with(@user)
	end

	def new
		redirect_to edit_user_path(current_user)
	end

	def edit
	end

	def create

		@user = current_user
		respond_with(@user)
	end

	def update
		
		# email and sms settings
		@user.allow_email = false if user_params[:allow_email].nil?
		@user.allow_sms = false if user_params[:allow_sms].nil?

		@user.update(user_params)

		# updating user's password
		unless params[:password].nil? || params[:password].empty?
			@user.password = params[:password]
			@user.password_confirmation = params[:password]
			@user.save!
		end

		if @user.errors.empty?
			redirect_to user_path(@user)
		else
			flash[:errors] = @user.errors.collect{|name, message| message}
			redirect_to edit_user_path(@user)
		end
	end

	def update_avatar
		# adding player avatar
		unless params[:avatar].nil? || params[:avatar].empty?
			begin
				avatar = PlayerAvatar.find(params[:avatar])
				@user.player_avatars.collect{|avatar| avatar.destroy}
				@user.player_avatars << avatar
			rescue Exception => ex
			end
		end
		design = render_to_string(:partial => "users/user_avatar", :locals => {:user => @user}, :layout => false )
		render json: { :design => design }, :status => 200
	end

	def team_feeds
		begin
			design = render_to_string(:partial => "teams/team_feeds", :locals => {:teams => current_user.teams, :allow_user_to_message => false}, :layout => false)
			render json: { :design => design }, :status => 200
		rescue Exception => e
		end
	end

	def destroy
		@user.destroy
		respond_with(@user)
	end

	private
		def set_user
			@user = current_user
		end

		def user_params
			params.permit(:name, :first_name, :last_name, :dob, :phone, :gender, :city, :country, :state, :allow_email, :allow_sms)
		end
end

app/helpers/users_helper.rb
module UsersHelper

	# for devise login from different controller
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:id => "update-user-form" , :class=>"editusers"}) do |f| %>
	<input type="hidden" id="user" name="user" value="<%= current_user.id %>">

	<div class="row">
		<div class="col-xs-12">
			<div class="grid simple">
				<div class="grid-title no-border">
					<h4>Edit <span class="semi-bold">Account</span></h4>
				
					<% if flash[:errors] and !flash[:errors].empty? %>
						<div id="devise-errors"> <ul>
								<%= flash[:errors].collect{|error| content_tag(:li, " #{error}", :class => "fa fa-caret-right col-lg-12 text-danger") }.join().html_safe %>
						</ul> </div>
					<% end %>
				</div>
						
				<div class="grid-body no-border">
					<div class="row">
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="form-group">
								<label class="form-label">First Name</label>
								<div class="controls">
									<input type="text" name="first_name" class="form-control" value="<%= @user.first_name.titleize if @user.first_name %>">
								</div>
							</div>
						</div>
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="form-group">
								<label class="form-label">Last Name</label>
								<div class="controls">
								<input type="text" name="last_name" class="form-control" value="<%= @user.last_name.titleize if @user.last_name %>">
								</div>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="form-group">
								<label class="form-label">Email</label>
								<div class="controls">
								<input type="email" name="email" class="form-control" value="<%= @user.email %>">
								</div>
							</div>
						</div>
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="form-group">
								<label class="form-label">Phone</label>
								<div class="controls">
									<input type="text" name="phone" class="form-control" value="<%= @user.phone %>">
								</div>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="form-group">
								<label class="form-label">Date of Birth</label>
								<div class="controls">
									<div class="input-append success date full-width no-padding">
										<input type="text" class="datepicker" name="dob" class="form-control" value="<%= @user.dob.strftime('%e %B, %Y') if @user.dob %>">
										<span class="add-on">
											<span class="arrow"></span>
											<i class="fa fa-th"></i>
										</span>
									</div>
								</div>
							</div> 
						</div>
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="form-group">
								<label class="form-label">Gender</label>
								<div class="controls">
									<select class="source-nosearch" name="gender" style="width:100%">
										<% GENDER.each do |gender| %>
											<option value="<%= gender %>" <%= selected = "selected" if @user.gender and (@user.gender.downcase == gender.downcase) %> >
												<%= gender.titleize %>
											</option>
										<% end %>
									</select>
								</div>
							</div>
						</div> 
					</div>

					<div class="row">
						<div class="col-xs-12">
							<div class="form-group">
							<label class="form-label">Password</label>
							<span class="help">only needed if you update password</span>
								<div class="controls">
								<input type="password" name="password" class="form-control">
								</div>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-12 col-sm-12 col-xs-12">
							<div class="row">
								<div class="col-md-4 col-xs-12">
									<div class="form-group">
										<label class="form-label">City</label>
										<div class="controls">
											<input type="text" name="city" class="form-control" value="<%= @user.city.titleize if @user.city %>">
										</div>
									</div>
								</div>
								
								<div class="col-md-4 col-xs-12">
									<div class="form-group">
									<label class="form-label">Country</label>
										<div class="controls">
										<select class="source-nosearch" name="country" style="width:100%">
											<option value=""> Select Country </option>

											<% COUNTRIES.each do |country| %>
												<option value="<%= country.first%>" <%= selected = "selected" if @user.country and @user.country.downcase == country.last.downcase %>>
													<%= country.last %>
												</option>
											<% end %>
										</select>
										</div>
									</div>
								</div>

								<div class="col-md-4 col-xs-12">
									<div class="form-group">
										<label class="form-label">State</label>
										<div class="controls">
											<select class="source" style="width:100%" name="state">
												<option value=""> Select State </option>
												
												<% STATES.each do |state| %>
													<option value="<%= state.first%>" <%= selected = "selected" if @user.state and @user.state.downcase == state.first.downcase %>>
														<%= state.last %>
													</option>
												<% end %>
											</select>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="grid-title no-border">
					<h4>Notification <span class="semi-bold">Options</span></h4>
				</div>
						
				<div class="grid-body no-border">
					<div class="row">
						<div class="col-md-6 col-xs-12 m-b-15">
							<div class="checkbox">
								<input id="allow_sms" type="checkbox" name="allow_sms" value="true" <%= checked = "checked" if @user.allow_sms %>>
								<label for="allow_sms">SMS</label>

								<input id="allow_email" type="checkbox" name="allow_email" value="true" <%= checked = "checked" if @user.allow_email %>>
								<label for="allow_email">E-Mail</label>
							
								<p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquan lorem ante, dapibus in, viverra quis, feugiat a, tellus. </p>
							</div>
						</div>
						<div class="col-md-6 col-xs-12">
							<div class="checkbox">
								<input id="yes" type="checkbox" name="optionyes" value="yes" checked="checked">
								<label for="yes">Terms and Conditions</label>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, </p>
							</div>
						</div>
					</div>
				</div>

				<div class="grid-body no-border">
					<div class="row">
						<div class="col-md-6 col-xs-6">
							<button type="submit" class="btn btn-primary btn-cons">Save Settings</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_user_avatar.html.erb
<% pic = user.player_avatars.empty? ? "/users/missing.png" : user.player_avatars.last.avatar(:original) %>
<img width="35" height="35" data-src-retina="<%= pic %>" data-src="<%= pic %>" src="<%= pic %>" alt="">

app/views/users/edit.html.erb
<%= render :partial => "layouts/header" %>

<!-- BEGIN CONTENT -->
<div class="page-container row-fluid">
	<%= render :partial => "layouts/side_panel" %>

	<!-- BEGIN PAGE CONTAINER-->
	<div class="page-content">
		<div class="content">
			<div class="row">
				<div class="col-sm-12 col-md-12 col-lg-9">
					<div class=" tiles white col-md-12 no-padding profile-pix">
						<div class="overlayer top-right">
							<div class="overlayer-wrapper">
								<div class="padding-10 ">
									<button type="button" class="btn btn-success btn-small" data-toggle="modal" data-target="#edit-picture">
										<i class="fa fa-pencil"></i>&nbsp;&nbsp; Edit Picture
									</button>
								</div>
							</div>
						</div>

						<div class="tiles green cover-pic-wrapper">
							<img src="/assets/cover_pic.png" alt="">
						</div>

						<div class="tiles white">
							<div class="row">
								<div class="col-md-3 col-sm-2" >
									<div class="user-profile-pic">
										<%= render :partial => "users/user_avatar", :locals => {:user => @user} %>
									</div>
								</div>
								
								<div class="col-md-8 col-sm-8 no-padding">
									<div class="profile-name">
										<h2><%= @user.name.titleize %></h2>
										<h6>Member since <%= @user.created_at.strftime("%B %d, %Y") %></h6>
									</div>
								</div>
							</div>
						</div>
					</div>

					<%= render :partial => "users/form" %>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="edit-picture" tabindex="-1" role="dialog" aria-labelledby="edit-picture" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<%= render :partial => "player_avatars/form", :locals => {:player_avatar => PlayerAvatar.new } %>
			</div>
			<div class="modal-body">
				<div class="modal-footer">
					<button type="button" class="btn btn-success update-avatar"> Update </button>
					<button type="button" class="btn btn-default" data-dismiss="modal"> Close </button>
				</div>
			</div>
		</div>
	</div>
</div>

<%= render :partial => "teams/form", :locals => { :team => Team.new, :team_avatar => TeamAvatar.new } %>
<%= render :partial => "teams/join_team" %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= render :partial => "layouts/header" %>

<!-- BEGIN CONTENT -->
<div class="page-container row-fluid">
	<%= render :partial => "layouts/side_panel" %>

	<!-- BEGIN PAGE CONTAINER-->
	<div class="page-content">
		<div class="content">
			<div class="row">
				<div class="col-sm-12 col-md-12 col-lg-9">
					<div class=" tiles white col-md-12 no-padding profile-pix">

						<!-- edit profile button visible for current user only -->
						<% if @user == current_user %>
							<div class="overlayer top-right">
								<div class="overlayer-wrapper">
									<div class="padding-10 ">
										<a href="<%= settings_path %>" class="btn btn-success btn-small">
											<i class="fa fa-pencil"></i>&nbsp;&nbsp; Edit Profile
										</a>
									</div>
								</div>
							</div>
						<% end %>

						<div class="tiles green cover-pic-wrapper">
							<img src="/assets/cover_pic.png" alt="">
						</div>

						<div class="tiles white">
							<div class="row">
								<div class="col-md-3 col-sm-2" >
									<div class="user-profile-pic">
										<%= render :partial => "users/user_avatar", :locals => {:user => @user} %>
									</div>
								</div>

								<div class="col-md-8 col-sm-8 no-padding">
									<div class="profile-name">
										<h2><%= @user.name.titleize %></h2>
										<h6>Member since <%= @user.created_at.strftime("%B %d, %Y") %></h6>
									</div>
								</div>
							</div>
						</div>
					</div>

				<div class="row">
					<div class="col-xs-12">
						<div class="grid simple">
							<div class="grid-title no-border">
								<h4>Your <span class="semi-bold">Profile</span></h4>
							</div>
						<div class="grid-body no-border">
							<div class="row">
								<div class="col-md-6 col-sm-6 col-xs-12">
									<div class="form-group">
										<label class="form-label">First Name</label>
										<div class="controls profile-info">
											<p><%= @user.first_name.titleize if @user.first_name %></p>
										</div>
									</div>
								</div>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<div class="form-group">
										<label class="form-label">Last Name</label>
										<div class="controls">
											<p><%= @user.last_name.titleize if @user.last_name %></p>
										</div>
									</div>
								</div>
							</div>


							<div class="row">
								<div class="col-md-6 col-sm-6 col-xs-12">
									<div class="form-group">
										<label class="form-label">Email</label>
										<div class="controls">
											<p><%= @user.email %></p>
										</div>
									</div>
								</div>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<div class="form-group">
										<label class="form-label">Phone</label>
										<div class="controls">
											<p><%= @user.phone %></p>
										</div>
									</div>
								</div>
							</div>
							
							<div class="row">
								<div class="col-md-6 col-sm-6 col-xs-12">
									<div class="form-group">
										<label class="form-label">Date of Birth</label>
										<div class="controls">
											<p><%= @user.dob.strftime("%d.%m.%Y") if @user.dob %></p>
										</div>
									</div>
								</div>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<div class="form-group">
										<label class="form-label">Gender</label>
										<div class="controls">
											<p><%= @user.gender.titleize if @user.gender %></p>
										</div>
									</div>
								</div> 
							</div>

							<div class="row">
								<div class="col-xs-12">
									<div class="form-group">
										<label class="form-label">Password</label>
										<div class="controls">
											<p>*******</p>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="row">
										<div class="col-md-4 col-xs-12">
											<div class="form-group">
												<label class="form-label">City</label>
												<div class="controls">
													<p><%= @user.city.titleize if @user.city %></p>
												</div>
											</div>
										</div>
										<div class="col-md-4 col-xs-12">
											<div class="form-group">
												<label class="form-label">Country</label>
												<div class="controls">
													<p><%= COUNTRIES.collect{|code, name| name.titleize if @user.country and code.downcase == @user.country.downcase }.compact.first %></p>
												</div>
											</div>
										</div>
										<div class="col-md-4 col-xs-12">
											<div class="form-group">
												<label class="form-label">State</label>
												<div class="controls">
													<p><%= STATES.collect{|code, name| name.titleize if @user.state and code.downcase == @user.state.downcase }.compact.first %></p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12">
									<div class="form-group">
										<label class="form-label">Status</label>
										<div class="controls">
											<p>available</p>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12">
									<div class="form-group">
										<label class="form-label">Facebook Settings</label>
										<div class="controls">
											<p>floriauck</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<%= render :partial => "teams/form", :locals => { :team => Team.new, :team_avatar => TeamAvatar.new } %>
<%= render :partial => "teams/join_team" %>