config/routes.rb
Rails.application.routes.draw do
  resources :events do
    member do
      post "rsvp"
      post "cancel"
    end
  end

  resources :teams do
    member do
      post "add_player"
      post "message"
      get "team_feeds"
      put "update_player"
      delete "delete_player"
    end

    collection do
      post "join"
      get "check_code"
    end
  end
  resources :team_avatars
  
  resources :players
  resources :player_avatars

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  resources :users do
    member do
      put "update_avatar"
      get "team_feeds"
    end
  end

  get "/dashboard", :to => "static#dashboard"
  get "/invitation_response", :to => "static#invitation_response"
  post "/sms_response", :to => "static#sms_response"
  get "/welcome", :to => "static#welcome"

  get "/settings", :to => "users#edit"
  root "static#landing"
  post '/email_processor' => 'griddler/emails#create'

end

app/models/event.rb
require "sanitize"
require "twilio-ruby"

class Event < ActiveRecord::Base
	include Webhookable
	belongs_to :team
	has_many :rsvps, :dependent => :destroy
	has_many :event_invitations, :dependent => :destroy

	validates :title, :presence => true, :length => { :minimum => 5}
	validates_presence_of :date
	validates :time, :presence => true

	before_save do
		self.title = self.title.downcase if self.title
		self.opponent = self.opponent.downcase if self.opponent
		self.category = self.category.downcase if self.category

		self.opponent = nil unless self.category == "game"
	end

	def users_in
		self.rsvps.in.collect{|rsvp| rsvp.user}
	end

	def users_out
		self.rsvps.out.collect{|rsvp| rsvp.user}
	end

	def users_not_sure
		self.rsvps.maybe.collect{|rsvp| rsvp.user}
	end

	def admin?(user)
		self.team.admin?(user)
	end

	# cron to send event invitations
	def self.initial_notifications
		# get events whose initial invitation isn't sent
		events = Event.where(:initial_call => false, :status => nil)

		events.each do|event|
			# combining event date and time into datetime for validation
			# send email when X hours remains in event's start
			event_datetime = DateTime.new(event.date.year, event.date.month, event.date.day, event.time.hour, event.time.min, event.time.sec, event.time.zone)
			next unless (DateTime.now .. DateTime.now + INVITATION_CONFIG[:initial_call].hour).cover?(event_datetime)

			# send invitation to every user, except admin
			event.team.users.each do |user|
				begin
					unless event.team.admin == user
						invitation = EventInvitation.where(:sender => event.team.admin, :reciever => user, :event => event).first_or_create
						invitation.update_attributes(:token => Digest::MD5.hexdigest(event.team.admin.email + user.email + event.id.to_s + Time.now.to_s))
						mail = EventInvitationMailer.send_event_invitation(invitation)

						mail.deliver! if user.allow_email
						send_text_message(user.phone, mail.subject, mail.body.to_s) if user.phone and user.allow_sms
					end
				rescue Exception => ex
				end
			end
			event.update_attributes(:initial_call => true)
		end
	end

	#cron to send event invitations only to maybe
	def self.reminder_notifications
		# send event invitation to those users whose response is "Maybe, Not Sure"
		events = Event.where(:reminder_call => false, :initial_call => true)
		events.each do|event|
			# combining event date and time into datetime for validation
			# send email when X hours remains in event's start
			event_datetime = DateTime.new(event.date.year, event.date.month, event.date.day, event.time.hour, event.time.min, event.time.sec, event.time.zone)
			next unless (DateTime.now .. DateTime.now + INVITATION_CONFIG[:reminder_call].hour).cover?(event_datetime)

			# send invitation to user whose status is not sure
			event.users_not_sure.each do |user|
				begin
					unless event.team.admin == user
						invitation = EventInvitation.where(:sender => event.team.admin, :reciever => user, :event => event).first_or_create
						invitation.update_attributes(:token => Digest::MD5.hexdigest(event.team.admin.email + user.email + event.id.to_s + Time.now.to_s))
						mail = EventInvitationMailer.send_event_invitation(invitation)

						mail.deliver! if user.allow_email
						send_text_message(user.phone, mail.subject, mail.body.to_s) if user.phone and user.allow_sms
					end
				rescue Exception => ex
				end
			end
			event.update_attributes(:reminder_call => true)
		end
	end

	#cron to send event's final invitations to all users with extra information
	def self.final_notifications
		# send event invitation to all users
		events = Event.where(:final_call => false, :initial_call => true, :reminder_call => true)
		events.each do|event|
			# combining event date and time into datetime for validation
			# send email when X hours remains in event's start
			event_datetime = DateTime.new(event.date.year, event.date.month, event.date.day, event.time.hour, event.time.min, event.time.sec, event.time.zone)
			next unless (DateTime.now .. DateTime.now + INVITATION_CONFIG[:final_call].hour).cover?(event_datetime)

			# send invitation to all users
			event.team.users.each do |user|
				begin
					unless event.team.admin == user
						invitation = EventInvitation.where(:sender => event.team.admin, :reciever => user, :event => event).first
						mail = EventInvitationMailer.invitation_final_report(invitation)

						mail.deliver! if user.allow_email
						send_text_message(user.phone, mail.subject, mail.body.to_s) if user.phone and user.allow_sms
					end
				rescue Exception => ex
				end
			end
			event.update_attributes(:final_call => true)
		end
	end

	def self.send_text_message(to, subject, body, from = nil)
		TWILIO_CLIENT.account.messages.create(:from => from || TWILIO_CONFIG[:number], :to => to, :body => "#{subject}\n#{sanitize_to_plain_text(body)}")
	end

	def self.weekly_mail
		teams = Team.all
		teams.each do |team|
			events = team.events.where(:date=>Time.now..Time.now.next_week,:status => nil)
			unless events.empty?
				users = team.users
				users.each do |user|
					mail = EventInvitationMailer.weekly_events(user,events)
					mail.deliver! if user.allow_email
				end
			end
			
		end
	end

	def self.process_email
	end
	
	def self.sanitize_to_plain_text(body)
		body = Sanitize.fragment(body.to_s, :elements => ["a"], :attributes => {"a" => ["href"]})
		Nokogiri::HTML(body).xpath("//a").each do |tag|
			body = body.gsub(tag.to_html, tag.text + "\n" + tag.attributes["href"].value)
		end
		body.squeeze(" ").gsub("\t", "").gsub("\n ", "\n").gsub(/[\n]+/, "\n");
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_event, only: [:show, :edit, :update, :destroy, :rsvp]
	respond_to :html

	def index
		@events = Event.all
		respond_with(@events)
	end

	def show
		respond_with(@event)
	end

	def new
		render :partial => "events/form", :locals => {:event => Event.new}, :layout => false
	end

	def edit
	end

	def create
		begin
			team = Team.find(params[:team_id])
			@event = Event.new(event_params)
			if team and team.admin?(current_user)
				if @event.save
					team.events << @event

					design = render_to_string(:partial => "teams/team_events", :locals => { :team => team }, :layout => false )
					render json: { :design => design }, :status => 200
				else
					render json: { error: @event.errors.full_messages.join(',')}, :status => 400
				end
			else
				render json: { alert: "You don't have permissions to add event in team #{@team.name.titleize}"}, :status => 200
			end
		rescue Exception => ex
			render json: { error: ex.message}, :status => 400
		end
	end

	def rsvp
		rsvp = @event.rsvps.user_rvsp(current_user.id).first_or_initialize
		rsvp.response = params[:response].downcase
		rsvp.save!

		render :partial => "events/event_details", :locals => { :event => @event }

	end

	def update
		begin
			team = Team.find(params[:team_id])
			if team && team.admin?(current_user)
				@event.update(event_params)

				if params[:dashboard] == "true"
					design = render_to_string(:partial => "events/user_events", :locals => { :user_events => current_user.reload.get_all_events }, :layout => false )
				else
					design = render_to_string(:partial => "teams/team_events", :locals => { :team => team }, :layout => false )
				end

				render json: { :design => design }, :status => 200
			else
				render json: { :alert => "You don't have permissions to delete event #{event.title.titleize}." }, :status => 200
			end
		rescue Exception => ex
			render json: { :error => ex.message }, :status => 400
		end
	end

	def destroy
		begin
			team = @event.team
			if team && team.admin?(current_user)
				@event.destroy
				if params[:dashboard] == "true"
					design = render_to_string(:partial => "events/user_events", :locals => { :user_events => current_user.reload.get_all_events }, :layout => false )
				else
					design = render_to_string(:partial => "teams/team_events", :locals => { :team => team }, :layout => false )
				end
				render json: { :design => design }, :status => 200
			else
				render json: { :alert => "You don't have permissions to delete event #{event.title.titleize}." }, :status => 200
			end
		rescue Exception => ex
			render json: { :error => ex.message }, :status => 400
		end
	end

	def cancel
		begin
			event = Event.find(params[:id])
			team = event.team
			if team && team.admin?(current_user)
				event.update(status_params)
				event.team.users.each do |user|
					unless event.team.admin == user
						mail = EventInvitationMailer.cancel_event(user,team,event)
						mail.deliver! if user.allow_email
					end
				end
				if params[:dashboard] == "true"
					design = render_to_string(:partial => "events/user_events", :locals => { :user_events => current_user.reload.get_all_events }, :layout => false )
				else
					design = render_to_string(:partial => "teams/team_events", :locals => { :team => team }, :layout => false )
				end
				render json: { :design => design }, :status => 200
			else
				render json: { :alert => "You don't have permissions to delete event #{event.title.titleize}." }, :status => 200
			end
		rescue Exception => ex
			render json: { :error => ex.message }, :status => 400
		end
	end
	private
	def set_event
		@event = Event.find(params[:id])
	end

	def status_params
		params.permit(:status)
	end

	def event_params
		params.permit(:title, :category, :opponent, :date, :time, :note, :team_id, :where)
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_details.html.erb
<div class="event-wrap widget-item style-b">
	<input type="hidden" class="event_id" name="event_id" value="<%= event.id %>">
	<div class="row">
		<div class="tiles white border-right sm-bottom-30">
			<div class="controller pull-right">
				<% if event.admin?(current_user) %>
					<a data-toggle="modal" data-target="#add_event<%= event.id %>" class="edit" href="#">
						<i class="fa fa-pencil-square-o"></i>
					</a>
				<% end %>
			</div>
			<div class="col-md-6 col-lg-6 col-sm-5 col-xs-12 p-b-15 p-t-15">
				<div>
					<h2>
						<%= event.time.strftime("%I:%M") %>
						<span class="time-day">
							<%= event.time.strftime("%p") %>
						</span>
					</h2>
					<h3>
						<%= event.category.capitalize if event.category %>
					</h3>
				</div>
				
				<h5 class="event-team-name">
					<span>Group:</span>
					<%= event.team.name.titleize %>
				</h5>
				<h5 class="event-team-name">
					<span>Where:</span>
					<%= event.where if event.where %>
					<a href="#">(map)</a>
				</h5>
			</div>
			<div class="col-md-6 col-lg-6 col-sm-7 col-xs-12 p-b-15 p-t-15">
				<div class="run listit">
					<%= render :partial => "events/rsvp_list", :locals => { :event => event } %>
				</div>
				<% a = event.rsvps.collect{|user| user.user_id} %>
					<%= render :partial => "events/events_response", :locals => { :event => event, :user=>a } if  a.include? current_user.id %>
					<%= render :partial => "events/rsvp_questions", :locals => { :event => event } unless  a.include? current_user.id %>
			</div>
		</div>
	</div>
</div>

app/views/events/_events_response.html.erb
<% response = event.rsvps.where(:user_id=>current_user.id).first.response if user.include? current_user.id %>
<div>
	<p class="run-question">
		<%= "Your RSVP: #{response}" if  user.include? current_user.id %>
	</p>
	<div class="run-btns">
		<div class="left source-code" style="display:block;">
			<a data-toggle="modal" data-target="#change_event_response<%= event.id%>" href="#" style="color:rgb(91, 168, 95);">
				Change
			</a>
		</div>
	</div>
</div>
<%= render :partial => "events/rsvp_change_options", :locals => { :event => event } %>

app/views/events/_events_schedule.html.erb
<% events = events.collect{|group| group.last}.flatten %>

<h3>Schedule: <span>All</span></h3>
<div class="grid-body no-border no-padding">
	<div class="table-responsive">
		<table class="table table-condensed team-schedule">
			<thead>
				<th style="width:16%">Team</th>
				<th style="width:10%">Date</th>
				<th style="width:4%">Time</th>
				<th style="width:16%">Event</th>
				<th style="width:15%">Site</th>
				<th style="width:4%">Score</th>
				<th style="width:3%">W/L</th>
			</thead>
			<tbody>
				<% events.each do |event| %>
					<tr>
						<% if event.status.nil? || (event.status.include?("cancel") && event.team.admin?(current_user)) %>
							<% if Time.now.to_date < event.date %>
								<td class="v-align-middle"> <%= event.team.name.titleize %> </td>
								<td class="v-align-middle"> <%= event.date.strftime("%a %d/%m") %> </td>
								<td class="v-align-middle"> <%= event.time.strftime("%H:%M") %> </td>
								<td class="v-align-middle muted"><%= event.title.titleize %> </td>
								<td class="muted"><%= event.where.titleize unless event.where.nil? %> </td>
								<td class="v-align-middle">62:48</td>
								<td class="v-align-middle">W</td>
							<% end %>
							<% if Time.now.to_date == event.date %>
									<% if Time.now.strftime("%I:%M %p")<= event.time.strftime("%I:%M %p") %>
										<td class="v-align-middle"> <%= event.team.name.titleize %> </td>
										<td class="v-align-middle"> <%= event.date.strftime("%a %d/%m") %> </td>
										<td class="v-align-middle"> <%= event.time.strftime("%H:%M") %> </td>
										<td class="v-align-middle muted"><%= event.title.titleize %> </td>
										<td class="muted"><%= event.where.titleize unless event.where.nil? %> </td>
										<td class="v-align-middle">62:48</td>
										<td class="v-align-middle">W</td>
								<% end %>
							<% end %>
						<% end %>
					</tr>
				<% end %>
			 </tbody>
		</table>
	</div>
</div>

app/views/events/_first_event.html.erb
<% event ||= Event.new %>

<div class="modal fade" id="add_event<%= event.id %>" tabindex="-1" role="dialog" aria-labelledby="add_event" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content event-modal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					×
				</button>
				<i class="fa fa-calendar-o fa-7x"></i>
				<h4 id="" class="semi-bold">Add an Event.</h4>
			</div>

			<%= form_for(event, :html => {:id => "add-first-event"}) do |f| %>
				<div class="modal-body">
					<div class="row form-row">
						<div class="col-md-12 select-container">
							<select name="team_id" id="team_id" class="source form-control" style="width:100%">
								<option value="">Please Select Team</option>
								<% current_user.teams.each do |team| %>
									<option value="<%= team.id %>"><%= team.name.titleize %></option>
								<% end %>
							</select>
						</div>

						<div class="col-md-12">
							<input type="text" class="form-control" name="title" placeholder="Event Title" value="<%= event.title.titleize if event.title %>">
						</div>
					</div>

					<div class="row form-row">
						<div class="col-md-12">
							<div class="radio no-brd toggles">
								<input id="practice<%=event.id%>" type="radio" name="category" value="practice" <%= checked = "checked" if event.category == "practice" %> >
								<label for="practice<%=event.id%>">Practice</label>
								<input id="game<%=event.id%>" type="radio" name="category" class="game" value="game" <%= checked = "checked" if event.category == "game" %> >
								<label for="game<%=event.id%>">Game</label>								
								<input id="pickup<%=event.id%>" type="radio" name="category" value="pickup" <%= checked = "checked" if event.category == "pickup" %> >
								<label for="pickup<%=event.id%>">Pickup</label>		
								<input id="other<%=event.id%>" type="radio" name="category" value="other" <%= checked = "checked" if event.category == "other" %> >
								<label for="other<%=event.id%>">Other</label>
							</div>
						</div>
					</div>

					<div class="row form-row collapse game" <%= "style=display:block" if event.category == "game" %>>
						<div class="col-md-12">
							<input type="text" class="form-control" name="opponent" placeholder="Opponent" value="<%= event.opponent.titleize if event.opponent %>">
						</div>
					</div>

					<div class="row form-row">
						<div class="col-md-6">
							<input type="text" name="date" class="datepicker form-control" placeholder="Date" value="<%= event.date.strftime('%e %B, %Y') if event.date %>">
						</div>
						<div class="col-md-6">
							<input type="text" name="time" class="timepicker form-control" placeholder="Time" value="<%= event.time.strftime('%I:%M %p') if event.time %>" >
						</div>

					</div>
					<div class="row form-row">
						<div class="col-md-12">
							<textarea id="text-editor" name="note" placeholder="Enter Note about this Event ..." class="form-control" rows="3"><%= event.note %></textarea>
						</div>
					</div>
					<div class="row form-row">
						<div class="col-md-12" id="event-message">
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<% if event.new_record? %>
						<button type="button" class="btn btn-default" data-dismiss="modal">
							Close
						</button>
						<button type="submit" class="btn btn-primary">Add Event</button>
					<% else %>
						<input type="hidden" class="event_id" name="event_id" value="<%= event.id %>">
						<input type="hidden" class="team_id" name="team_id" value="<%= event.team.id %>">

						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="button" class="btn btn-danger event-remove" >
							Remove Event
						</button>
						<button type="submit" class="btn btn-primary event-update">
							Update Event
						</button>
					<% end %>
				</div>
			</div>
		<% end %>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

app/views/events/_form.html.erb
<% event ||= Event.new %>

<div class="modal fade" id="add_event<%= event.id.to_s %>" tabindex="-1" role="dialog" aria-labelledby="add_event" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content event-modal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					×
				</button>
				<i class="fa fa-calendar-o fa-7x"></i>
				<h4 id="" class="semi-bold">Add an Event.</h4>
			</div>
			<% form_id = event.new_record? ? "add-event-form" : "" %>

			<%= form_for(event, :html => {:id => form_id}) do |f| %>
				<div class="modal-body">
					<div class="row form-row">
						<div class="col-md-12">
							<input type="text" class="form-control" name="title" placeholder="Event Title" value="<%= event.title.titleize if event.title %>">
						</div>
					</div>

					<div class="row form-row">
						<div class="col-md-12">
							<div class="radio no-brd toggles">
								<input id="practice<%=event.id%>" type="radio" name="category" value="practice" <%= checked = "checked" if event.category == "practice" %> >
								<label for="practice<%=event.id%>">Practice</label>
								<input id="game<%=event.id%>" type="radio" name="category" class="game" value="game" <%= checked = "checked" if event.category == "game" %> >
								<label for="game<%=event.id%>">Game</label>								
								<input id="pickup<%=event.id%>" type="radio" name="category" value="pickup" <%= checked = "checked" if event.category == "pickup" %> >
								<label for="pickup<%=event.id%>">Pickup</label>		
								<input id="other<%=event.id%>" type="radio" name="category" value="other" <%= checked = "checked" if event.category == "other" %> >
								<label for="other<%=event.id%>">Other</label>
							</div>
						</div>
					</div>

					<div class="row form-row collapse game" <%= "style=display:block" if event.category == "game" %>>
						<div class="col-md-12">
							<input type="text" class="form-control" name="opponent" placeholder="Opponent" value="<%= event.opponent.titleize if event.opponent %>">
						</div>
					</div>

					<div class="row form-row">
						<div class="col-md-6">
							<input type="text" name="date" class="datepicker form-control" placeholder="Date" value="<%= event.date.strftime('%e %B, %Y') if event.date %>">
						</div>
						<div class="col-md-6">
							<input type="text" name="time" class="timepicker form-control" placeholder="Time" value="<%= event.time.strftime('%I:%M %p') if event.time %>" >
						</div>

					</div>
					<div class="row form-row">
						<div class="col-md-12">
							<input type="text" class="form-control" name="where" placeholder="Where" value="<%= event.where.titleize if event.where %>">
						</div>
					</div>

					<div class="row form-row">
						<div class="col-md-12">
							<textarea id="text-editor" name="note" placeholder="Enter Note about this Event ..." class="form-control" rows="3"><%= event.note %></textarea>
						</div>
					</div>
					<div class="row form-row">
						<div class="col-md-12" id="event-message">
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<% if event.new_record? %>
						<button type="button" class="btn btn-default" data-dismiss="modal">
							Close
						</button>
						<button type="submit" class="btn btn-primary">Add Event</button>
					<% else %>
						<input type="hidden" class="event_id" name="event_id" value="<%= event.id %>">
						<input type="hidden" class="team_id" name="team_id" value="<%= event.team.id %>">

						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="button" class="btn btn-danger event-cancel" >
							Cancel Event
						</button>
						<button type="button" class="btn btn-danger event-remove" >
							Remove Event
						</button>
						<button type="submit" class="btn btn-primary event-update">
							Update Event
						</button>
					<% end %>
				</div>
			</div>
		<% end %>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

app/views/events/_rsvp_change_options.html.erb
<div class="modal" id="change_event_response<%= event.id %>" tabindex="-1" role="dialog" aria-labelledby="change_event_response" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content event-modal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					×
				</button>
				<h4 id="" class="semi-bold">Change Response</h4>
			</div>
			<div class="modal-body">

				<div class="run-btns">
					<div class="toggle-in left source-code">
						I confirm that I can came on <%= event.date.strftime("%A %B #{event.date.day.ordinalize}") if event.date %>, at <%= event.time.strftime('%I:%M %p') if event.time %> at <%= event.team.city if event.team %>.
					</div>
					<button class="btn in-btn btn-success" value="<%= event.id %>">In</button>
					<div class="toggle-maybe left source-code">
						I am not sure that I can came on <%= event.date.strftime("%A %B #{event.date.day.ordinalize}") if event.date %>, at <%= event.time.strftime('%I:%M %p') if event.time %> at <%= event.team.city if event.team %>.
					</div>
					<button class="btn maybe-btn btn-warning" value="<%= event.id %>">Maybe</button>
					<div class="toggle-out left source-code">
						I cannot attend event on <%= event.date.strftime("%A %B #{event.date.day.ordinalize}") if event.date %>, at <%= event.time.strftime('%I:%M %p') if event.time %> at <%= event.team.city if event.team %>.
					</div>
					<button class="btn out-btn btn-danger" value="<%= event.id %>" >Out</button>
				</div>
			</div>
			<div class="modal-footer">
			</div>
		</div>
	</div>
</div>

app/views/events/_rsvp_list.html.erb
<p class="event-ins in">
	<i class="fa fa-check"></i> 
	<a href="#" tabindex="0" class="run-count" data-toggle="popover" data-trigger="focus" title="" data-content="<%= event.users_in.collect{|user| user.name.titleize}.join(", ") %>">
		<strong> <%= event.rsvps.in.count %> </strong> IN
	</a>
</p>

<p class="event-ins maybe">
	<i class="fa fa-question-circle"></i>
	<a href="#" tabindex="0" class="run-count" data-toggle="popover" data-trigger="focus" title="" data-content="<%= event.users_not_sure.collect{|user| user.name.titleize}.join(", ") %>">
		<strong> <%= event.rsvps.maybe.count %> </strong> MAYBE
	</a>
</p>

<p class="event-ins out">
	<i class="fa fa-times-circle"></i>
	<a href="#" tabindex="0" class="run-count" data-toggle="popover" data-trigger="focus" title="" data-content="<%= event.users_out.collect{|user| user.name.titleize}.join(", ") %>">
		<strong> <%= event.rsvps.out.count %> </strong> OUT
	</a>
</p>

app/views/events/_rsvp_questions.html.erb
<p class="run-question">Are you In?!</p>
<div class="run-btns">
	<div class="toggle-in left source-code">
		I confirm that I can came on <%= event.date.strftime("%A %B #{event.date.day.ordinalize}") if event.date %>, at <%= event.time.strftime('%I:%M %p') if event.time %> at <%= event.team.city if event.team %>.
	</div>
	<button class="btn in-btn btn-success">In</button>
	<div class="toggle-maybe left source-code">
		I am not sure that I can came on <%= event.date.strftime("%A %B #{event.date.day.ordinalize}") if event.date %>, at <%= event.time.strftime('%I:%M %p') if event.time %> at <%= event.team.city if event.team %>.
	</div>
	<button class="btn maybe-btn btn-warning">Maybe</button>

	<div class="toggle-out left source-code">
		I cannot attend event on <%= event.date.strftime("%A %B #{event.date.day.ordinalize}") if event.date %>, at <%= event.time.strftime('%I:%M %p') if event.time %> at <%= event.team.city if event.team %>.
	</div>
	<button class="btn out-btn btn-danger">Out</button>
</div>

app/views/events/_user_events.html.erb
<% user_events.each do |date, events| %>
	<div class="cal-day">
		<% show_date = true %>
		<% events.each do |event| %>
			<% if event.status.nil? || (event.status.include?("cancel") && event.team.admin?(current_user)) %>
				<% if Time.now.to_date < event.date %>
					<% if show_date %>
						<h3><%= date.strftime("%A, %b #{date.day.ordinalize}") %></h3>
						<% show_date = false %>
					<% end %>
					<div class="e_detail">
						<%= render :partial => "events/event_details", :locals => { :event => event } %>
					</div>
				<% end %>
				<% if Time.now.to_date == event.date %>
					<% if Time.now.strftime("%I:%M %p")<= event.time.strftime("%I:%M %p") %>
						<% if show_date %>
							<h3><%= date.strftime("%A, %b #{date.day.ordinalize}") %></h3>
							<% show_date = false %>
						<% end %>
						<div class="e_detail">
							<%= render :partial => "events/event_details", :locals => { :event => event } %>
						</div>
					<% end %>
				<% end %>
				<%= render :partial => "events/form", :locals => { :event => event } %>
			<% end %>	
		<% end %>
	</div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Opponent</th>
      <th>Date</th>
      <th>Time</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.type %></td>
        <td><%= event.opponent %></td>
        <td><%= event.date %></td>
        <td><%= event.time %></td>
        <td><%= event.note %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Type:</strong>
  <%= @event.type %>
</p>

<p>
  <strong>Opponent:</strong>
  <%= @event.opponent %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<p>
  <strong>Note:</strong>
  <%= @event.note %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>