config/routes.rb
Rails.application.routes.draw do
  resources :events do
    member do
      post "rsvp"
      post "cancel"
    end
  end

  resources :teams do
    member do
      post "add_player"
      post "message"
      get "team_feeds"
      put "update_player"
      delete "delete_player"
    end

    collection do
      post "join"
      get "check_code"
    end
  end
  resources :team_avatars
  
  resources :players
  resources :player_avatars

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  resources :users do
    member do
      put "update_avatar"
      get "team_feeds"
    end
  end

  get "/dashboard", :to => "static#dashboard"
  get "/invitation_response", :to => "static#invitation_response"
  post "/sms_response", :to => "static#sms_response"
  get "/welcome", :to => "static#welcome"

  get "/settings", :to => "users#edit"
  root "static#landing"
  post '/email_processor' => 'griddler/emails#create'

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	before_action :set_player, only: [:show, :edit, :update, :destroy]

	# GET /players
	# GET /players.json
	def index
		@players = User.all
	end

	# GET /players/1
	# GET /players/1.json
	def show
	end

	# GET /players/new
	def new
		render :partial => "players/form", :locals => {:player => User.new}, :layout => false
	end

	# GET /players/1/edit
	def edit
	end

	# POST /players
	# POST /players.json
	def create
		@player = User.new(player_params)
		respond_to do |format|
			if @player.save
				format.html { redirect_to @player, notice: 'Player was successfully created.' }
				format.json { render :show, status: :created, location: @player }
			else
				format.html { render :new }
				format.json { render json: @player.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /players/1
	# PATCH/PUT /players/1.json
	def update
		respond_to do |format|
			if @player.update(player_params)
				format.html { redirect_to @player, notice: 'Player was successfully updated.' }
				format.json { render :show, status: :ok, location: @player }
			else
				format.html { render :edit }
				format.json { render json: @player.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /players/1
	# DELETE /players/1.json
	def destroy
		@player.destroy
		respond_to do |format|
			format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_player
			@player = User.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def player_params
			params.require(:player).permit(:name, :phone, :email, :gender)
		end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<div class="modal fade" id="add_player<%= player.id %>" tabindex="-1" role="dialog" aria-labelledby="add_player" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					
				<% if player.new_record? %>
					<%= render :partial => "player_avatars/form", :locals => {:player_avatar => PlayerAvatar.new } %>
					<h4 id="" class="semi-bold">Add Player.</h4>
				<% else %>
					<h4 id="" class="semi-bold">Edit Player.</h4>
				<% end %>
				
			</div>
			<% form_id = player.new_record? ? "add-player-form" : "" %>
			<%= form_for(player,:html => { :id => form_id}) do |f| %>
				<% team_user = player.new_record? ? team_user = TeamsUser.new : TeamsUser.where(:user => player.id, :team =>team.id).first %>
					<% team_user.first_name = player.name.split(' ',2).first if (team_user.first_name.nil? || team_user.first_name.empty?) && !player.name.nil? %>
					<% team_user.last_name = player.name.split(' ',2).last if (team_user.last_name.nil? || team_user.last_name.empty?) && !player.name.nil? %>
				<div class="modal-body">
					<div class="row form-row">
						<div class="col-md-6">
							<input type="text" class="form-control" name="first_name" placeholder="First Name" value="<%= team_user.first_name if !team_user.to_s.empty? %>">
						</div>
						<div class="col-md-6">
							<input type="text" class="form-control" name="last_name" placeholder="Last Name" value="<%= team_user.last_name if !team_user.to_s.empty? %>">
						</div>
					</div>
					<div class="row form-row">
						<div class="col-md-12">
							<input type="text" class="form-control" name="email" placeholder="E-Mail" value="<%= player.email %>" <%= disabled = "disabled" unless player.email.to_s.empty? %>>
						</div>
					</div>
					<div class="row form-row">
						<div class="col-md-12">
							<input type="text" class="form-control" name="phone" placeholder="Phone" value="<%= player.phone %>"  <%= disabled = "disabled" unless player.phone.to_s.empty? %>>
						</div>
					</div>
					<div class="row form-row">
						<div class="col-md-12">
							<div class="radio no-brd">
								<input id="male-player<%=player.id%>" type="radio" name="gender" value="male" 
								<%= checked = "checked" if player.gender == "male" %> <%= disabled = "disabled" unless player.gender.to_s.empty? %>>
								<label for="male-player<%=player.id%>">Male</label>
								<input id="female-player<%=player.id%>" type="radio" name="gender" value="female" 
								<%= checked = "checked" if player.gender == "female" %><%= disabled = "disabled" unless player.gender.to_s.empty? %>>
								<label for="female-player<%=player.id%>">Female</label>
							</div>
						</div>
					</div>
					<div id="add-player-status" class="text-danger"></div>
				</div>
				<div class="modal-footer">
					<% if player.new_record? %>
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="submit" class="btn btn-primary" >Add Player</button>
					<% else %>
						<input type="hidden" class="user_id" name="user_id" value="<%= player.id %>">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="button" class="btn btn-danger player-remove" >
							Remove Player
						</button>
						<button type="submit" class="btn btn-primary player-update">
							Update Player
						</button>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>