config/routes.rb
Rails.application.routes.draw do
  resources :events do
    member do
      post "rsvp"
      post "cancel"
    end
  end

  resources :teams do
    member do
      post "add_player"
      post "message"
      get "team_feeds"
      put "update_player"
      delete "delete_player"
    end

    collection do
      post "join"
      get "check_code"
    end
  end
  resources :team_avatars
  
  resources :players
  resources :player_avatars

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  resources :users do
    member do
      put "update_avatar"
      get "team_feeds"
    end
  end

  get "/dashboard", :to => "static#dashboard"
  get "/invitation_response", :to => "static#invitation_response"
  post "/sms_response", :to => "static#sms_response"
  get "/welcome", :to => "static#welcome"

  get "/settings", :to => "users#edit"
  root "static#landing"
  post '/email_processor' => 'griddler/emails#create'

end

app/views/layouts/_header.html.erb
<!-- BEGIN HEADER -->
<div class="header navbar navbar-inverse">
	<!-- BEGIN TOP NAVIGATION BAR -->
	<div class="navbar-inner">
		<!-- BEGIN NAVIGATION HEADER -->
		<div class="header-seperation">
			<!-- BEGIN MOBILE HEADER -->
			<ul class="nav pull-left notifcation-center visible-xs" id="main-menu-toggle-wrapper">
				<li class="dropdown">
					<a id="main-menu-toggle" href="#main-menu" class="">
						<div class="iconset top-menu-toggle-white"></div>
					</a>
				</li>
			</ul>
			<!-- END MOBILE HEADER -->
			
			<!-- BEGIN LOGO -->
			<a href="/">
				<img src="/assets/logo-inverted.png" class="logo" alt="" data-src="/assets/logo-inverted.png" data-src-retina="/assets/logo2x.png"/>
			</a>
			<!-- END LOGO --> 

			<!-- BEGIN LOGO NAV BUTTONS -->
			<ul class="nav pull-right notifcation-center">
				<li class="quicklinks visible-xs">
					<a data-toggle="dropdown" class="dropdown-toggle pull-right" href="#" id="user-options">
						<div class="iconset top-settings"></div>
					</a>
					<ul class="dropdown-menu pull-right" role="menu" aria-labelledby="user-options">
						<li> <a href="<%= user_path(current_user) %>"> Account Profile </a> </li>
		
						<li> <a href="<%= settings_path %>"> Edit Account </a> </li>
						<li class="divider"> </li>
						<li>
							<a data-toggle="modal" data-target="#add_team" class="add-team-modal" href="#">
								<i class="fa fa-plus-circle"> </i> &nbsp;&nbsp;Add Team
							</a>
						</li>

						<li class="divider"> </li>
						<li>
							<a href="{path=LOGOUT}"> <i class="fa fa-power-off"> </i>&nbsp;&nbsp;Logout </a>
						</li>
					</ul>
				</li>
			</ul>
			<!-- END LOGO NAV BUTTONS -->
		</div>
		<!-- END NAVIGATION HEADER -->
		
		<!-- BEGIN CONTENT HEADER -->
		<div class="header-quick-nav"> 
			<!-- BEGIN HEADER LEFT SIDE SECTION -->
			<div class="pull-left">
				<ul class="nav quick-section mainnav">
					<li class="quicklinks">
						<a href="/" class=""> All Events </a>
					</li>

					<li class="quicklinks dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">
							Teams <span class="caret"> </span>
						</a>
						<ul class="dropdown-menu" role="menu">
							<% @teams.each do |team| %>
								<li>
									<a href="<%= team_path(team) %>"> <%= team.name.titleize %> </a>
								</li>
							<% end %>
							<li class="divider"> </li>
							<li>
								<a data-toggle="modal" data-target="#add_team" href="#" class=""><i class="fa fa-plus-circle"></i> Add Team</a>
							</li>
							<li>
								<a data-toggle="modal" data-target="#join-team" href="#" class="join-team-modal">
									<i class="fa fa-plus-circle"></i> Join Team
								</a>
							</li>
						</ul>
					</li>

					<% if @team and @team.admin?(current_user) %>
						<li class="quicklinks">
							<a data-toggle="modal" data-target="#add_event" href="#" class="">
								<i class="fa fa-calendar"></i> Add Event
							</a>
						</li>
						<li class="quicklinks">
							<a data-toggle="modal" data-target="#add_player" href="#" class="add-player-modal">
								<i class="fa fa-user"></i> Add Player
							</a>
						</li>
					<% end %>
					<li class="quicklinks">
						<a data-toggle="modal" data-target="#add_team" href="#" class="add-team-modal">
							<i class="fa fa-plus-circle"></i> Add Team
						</a>
					</li>
					<li class="quicklinks">
						<a data-toggle="modal" data-target="#join-team" href="#" class="join-team-modal">
							<i class="fa fa-plus-circle"></i> Join Team
						</a>
					</li>
				</ul>
			</div>
			<!-- END HEADER LEFT SIDE SECTION -->
				
			<!-- BEGIN HEADER RIGHT SIDE SECTION -->
			<div class="pull-right settings-section"> 
				<div class="chat-toggler">
					<!-- BEGIN PROFILE PICTURE -->
					<div class="profile-pic">
						<% pic = current_user.player_avatars.empty? ? "/users/missing.png" : current_user.player_avatars.last.avatar(:original) %>
						<img src="<%= pic %>" alt="" data-src="<%= pic %>" data-src-retina="/<%= pic %>" width="35" height="35" /> 
					</div>	
					<!-- END PROFILE PICTURE -->								
				</div>

				<!-- BEGIN HEADER NAV BUTTONS -->
				<ul class="nav quick-section">
					<!-- BEGIN SETTINGS -->
					<li class="quicklinks">
						<a data-toggle="dropdown" class="dropdown-toggle pull-right" href="#" id="user-options">		
							<div class="user-name-drop">
								<span> <%= current_user.name %> </span>
								<i class="fa fa-angle-down"></i>
							</div>
						</a>
						<ul class="dropdown-menu pull-right" role="menu" aria-labelledby="user-options">
							<li>
							<a href="<%= user_path(current_user) %>">Account Profile</a>
							</li>
							<li>
							<a href="<%= settings_path  %>">Edit Account</a>
							</li>
							<li class="divider"> </li>
							<li>
								<a href="#" data-toggle="modal" data-target="#add_team"> <i class="fa fa-plus-circle"> </i>&nbsp;&nbsp;
								Add Team</a>
							</li>
							<li class="divider"> </li>
							<li>
								<a href="<%= destroy_user_session_path %>" data-method="delete"><i class="fa fa-power-off"></i>&nbsp;&nbsp;Logout</a>
							</li>
						</ul>
					</li>
				</ul>
				<!-- END HEADER NAV BUTTONS -->
			</div>

			<div class="pull-right message-center-wrap">

				<!-- BEGIN NOTIFICATION CENTER -->
				<a href="#" class="dropdown-toggle" id="my-task-list" data-placement="bottom" data-content="" data-toggle="dropdown" data-original-title="Notifications">
					<div class="user-details">
						<div class="message-center">
							<i class="fa fa-envelope-o"></i>
						</div>
					</div> 
				</a>		
				<!-- END NOTIFICATION CENTER -->
			</div>
			<!-- END HEADER RIGHT SIDE SECTION -->
		</div> 
		<!-- END CONTENT HEADER --> 
	</div>
	<!-- END TOP NAVIGATION BAR --> 
</div>
<!-- END HEADER -->

app/views/layouts/_side_panel.html.erb
<div class="page-sidebar" id="main-menu"> 
	<div class="page-sidebar-wrapper" id="main-menu-wrapper">
		<!-- BEGIN MINI-PROFILE -->
		<div class="user-info-wrapper"> 
			<div class="profile-wrapper">
				<% pic = current_user.player_avatars.empty? ? "/users/missing.png" : current_user.player_avatars.last.avatar(:original) %>
				<img src="<%= pic %>" alt="" data-src="<%= pic %>" data-src-retina="<%= pic %>" width="69" height="69" />
			</div>

			<div class="user-info">
				<div class="greeting">Welcome</div>
				<div class="username"><%= current_user.name %></div>
			</div>
		</div>
		<!-- END MINI-PROFILE -->
		<!-- BEGIN SIDEBAR MENU --> 
		
		<ul>
			<!-- BEGIN SELECTED LINK -->
			<li class="start active">
				<a href="<%= dashboard_path %>">
					<i class="fa fa-calendar"></i>
					<span class="title">Events</span>
					<span class="selected"></span>
				</a>
			</li>
			<!-- END SELECTED LINK -->

			<!-- BEGIN ONE LEVEL MENU -->
			<li class="">
				<a href="javascript:;">
					<i class="fa fa-group"></i>
					<span class="title">Teams</span>
					<span class="arrow"></span>
				</a>
				<ul class="sub-menu">
					<% @teams.each do |team| %>
						<li> <a href="<%= team_path(team) %>"> <%= team.name.titleize %> </a> </li>
					<% end %>
				</ul>
			</li>
			<!-- END ONE LEVEL MENU -->

			<!-- END TWO LEVEL MENU --> 
			<li>
				<a href="#" data-toggle="modal" data-target="#add_team">
					<i class="fa fa-plus-circle"></i> Add Team
				</a>
			</li>

			<li>
				<a data-toggle="modal" data-target="#join-team" href="#" class="join-team-modal">
					<i class="fa fa-plus-circle"></i> Join Team
				</a>
			</li>

			<!-- BEGIN TWO LEVEL MENU -->
			<li class="">
				<a href="javascript:;">
					<i class="fa fa-gear"></i>
					<span class="title">Account</span>
					<span class="arrow"></span>
				</a>
				<ul class="sub-menu">
					<li><a href="<%= user_path(current_user) %>"> View Profile </a></li>
					<li><a href="<%= settings_path	%>">Edit Profile</a></li>
				</ul>
			</li>

			<li>
				<a href="<%= destroy_user_session_path %>" data-method="delete">
					<i class="fa fa-power-off"></i>Logout
				</a>
			</li>
		</ul>

		<div class="clearfix"></div>
		<!-- END SIDEBAR WIDGETS -->
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Run</title>
	<%= stylesheet_link_tag 'application', media: 'all' %>
	<%= csrf_meta_tags %>
</head>

<body class="">

	<%= yield %>
	
	<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/landing_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  
  <title>RU N?</title>
  
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="Florian Auckenthaler - designingit.com">

  <!-- Favicon /-->
  <link rel="shortcut icon" href="/assets/favicon.png" type="image/x-icon" />

  <%= stylesheet_link_tag "landing", media: 'all' %>
  <%= javascript_include_tag "landing" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<!-- Fade In of the Page -->
	<div class="loader"></div>

	<!-- Page Top Bar -->
	<div class="topBar">
		<div class="barInner row">
			<a href="/"> <h1 class="logo"> Are You In? </h1> </a>

			<nav id="nav">
				<a class="scrollTo" href="#first"> Tour </a>
				<a class="outline-button switch" href="#" gumby-trigger="#login"> Login </a>
				<a class="outline-button switch" href="#" gumby-trigger="#getstarted">
					Get Started
				</a>
			</nav>
    	</div>
	</div>

	<%= yield %>

</body>
</html>